# Second Part

## Глава 2

### Массив последовательностей

In [1]:
# Глава рассматривает различные последовательности: 
#     от знакомых list до bytes.

# Строки Unicode будут рассмотрены в Главе 4;
# Собственные последовательности - в Главе 10.

### Общие сведения о встроенных последовательностях

In [7]:
# Последовательности стандартной библиотеки реализованы на C:

#     - Контейнерные последовательности: [разных типов]
#           - list
#           - tuple
#           - collections.deque

#     - Плоские последовательности: [одного типа]
#           - str
#           - bytes
#           - bytearrey
#           - memoryview
#           - array.array

# В контейнерных последовательностях хранятся ссылки на объекты;
# В плоских последовательностях хранятся сами значения.

#     - Изменяемые последовательности:
#           - list
#           - bytearray
#           - array.array
#           - collections.deque
#           - memoryview

#     - Неизменяемые последовательности:
#           - tuple
#           - str
#           - bytes

### Списковое включение и генераторные выражения

In [9]:
# Списковое включение называют listcomp,
#     а генераторное выражение - genexp.

#### Списковое включение и удобочитаемость

In [10]:
symbols = '$π¿φ╖‡'

codes_loop = []
for symbol in symbols:
    codes_loop.append(ord(symbol))

codes_comp = [ord(symbol) for symbol in symbols]

assert codes_loop == codes_comp

In [11]:
# У списковых включений (начиная с python 3.) есть локальная область видимости;
# Переменняе, присвоенные внутри, остаются локальными - как с функциями.

In [ ]:
# Списковое включение создает список из любого итерируемого типа.

#### Сравнение спискового включения с map и filter

In [12]:
symbols = '$π¿φ╖‡'

ascii_comp = [ord(s) for s in symbols if ord(s) > 127]

ascii_funcs = list(filter(lambda c: c > 127, map(ord, symbols)))

assert ascii_comp == ascii_funcs

In [13]:
# При этом списковое включение не проигрывает по времени
#     композиции map и filter (утверждает Алекс Мартелли).

#### Декартовы произведения

In [17]:
# Декартово произведение - множество кортежей, 
#     включающих по одному элементу на каждого объекта-сомножителя.

# Длина результирующего списка равна 
#     произведению длин входных объектов.для 

# Декартово произведение R x S, где R = [A, B, C], S = [1, 2, 3, 4]:
# [ A1, A2, A3, A4,
#   B1, B2, B3, B4,
#   C1, C2, C3, C4,
#   D1, D2, D3, D4 ]

In [21]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts_comp = [(color, size) for color in colors
                              for size in sizes]
tshirts_loop = []
for color in colors:
    for size in sizes:
        tshirts_loop.append((color, size))

assert tshirts_comp == tshirts_loop

In [22]:
# Списковые включения умеют создавать списки;

# Для построения остальных последовательностей 
#     следует обратиться к генераторным выражениям.

#### Генераторные выражения

In [ ]:
# В отличие от спискового включения генераторное выражение экономит память,
#     т.к. отдает элементы по одному.

# Синтаксически генераторное выражение выглядит так же,
#     как списковое включение, но заключается в круглые скобки.

In [24]:
symbols = '$π¿φ╖‡'
tuple(ord(symbol) for symbol in symbols)

(36, 960, 191, 966, 9558, 8225)

In [25]:
import array
array.array('I', (ord(symbol) for symbol in symbols)) # 'I' - тип данных

array('I', [36, 960, 191, 966, 9558, 8225])

In [26]:
colors = ['black', 'white']
sized = ['S', 'M', 'L']

for tshirt in ('%s %s' % (c, s) for c in colors for s in sizes):
    print(tshirt) # генераторное выражение отдает по одному элементу за раз
                  # список, содержащий все элементы, не создается

black S
black M
black L
white S
white M
white L


### Кортеж - не просто изменяемый список

In [28]:
# У кортежей две функции:
#     - Использованиие в качестве "неизменяемых списков";
#     - В качестве записей с неименованными полями.

#### Кортежи как записи

In [30]:
# Каждый элемент кортежи содержит данные одного поля;
# Позиция кортежа отражает семантику поля.

In [32]:
lax_coordinates = (33.9425, -118.408056) # широта и долгота аэропорта
city, year, pop, chg, area = ('Tokio', 2003, 32450, 0.66, 8014)
                          # название, год, численность млн, динамика %, площадь
traveler_ids = [('USA', '31195855'), ('BRA', 'CE343567'), 
                ('ESP', 'XDA205856')] # (код_страны, номер_паспорта)
for passport in sorted(traveler_ids):
    print('%s/%s' % passport) # каждый элемент - отдельное поле

BRA/CE343567
ESP/XDA205856
USA/31195855


In [33]:
for country, _ in traveler_ids:
    print(country) # переменная _ - не интересующий нас элемент 

USA
BRA
ESP


#### Распаковка кортежа

In [37]:
lax_coordinates = (33.9425, -118.408056)
latitude, longitude = lax_coordinates # tuple unpacking
print(latitude, longitude)

# a, b = b, a

33.9425 -118.408056


In [40]:
t = (20, 8)

assert divmod(20,8) == divmod(*t)

quotient, remainder = divmod(*t)
quotient, remainder

(2, 4)

### Использование * для выборки лишних элементов

In [43]:
a, b, *rest = range(5)
a, b, rest

(0, 1, [2, 3, 4])

In [44]:
a, b, *rest = range(2)
a, b, rest

(0, 1, [])

In [45]:
a, *body, c, d = range(5)
a, body, c, d

(0, [1, 2], 3, 4)

#### Распаковка вложенного кортежа

In [50]:
metro_areas = [
    ('Tokyo', 'JP', 36.933, (35.689722, 139.691667)),
    ('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),
    ('Mexico City', 'MX', 20.142, (19.433333, -99.133333)),
    ('New-York-Newark', 'US', 20.104, (40.808611, -74.020386)),
    ('Sao Paulo', 'BR', 19.649, (-23.547778, -46.635833))
]
print('{:15} | {:^9} | {:^9}'.format('', 'lat.', 'long.'))
fmt = '{:15} | {:9.4f} | {:9.4f}'
for name, cc, pop, (latitude, longitude) in metro_areas:
    if longitude <= 0: # мегаполисы в западном полушарии
        print(fmt.format(name, latitude, longitude))

                |   lat.    |   long.  
Mexico City     |   19.4333 |  -99.1333
New-York-Newark |   40.8086 |  -74.0204
Sao Paulo       |  -23.5478 |  -46.6358


#### Именованные кортежи

In [52]:
# collections.namedtuple - фабрика подклассов tuple с именованными полями

In [53]:
from collections import namedtuple
City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689722, 139.691667))
tokyo

City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689722, 139.691667))

In [54]:
tokyo.coordinates

(35.689722, 139.691667)

In [55]:
tokyo[1]

'JP'

In [56]:
City._fields # кортеж с именами полей

('name', 'country', 'population', 'coordinates')

In [58]:
LatLong = namedtuple('LatLong', 'lat long')
delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613889, 77.208889))
delhi = City._make(delhi_data)
delhi._asdict() # возвращает словарь, построенный по именованному кортежу

OrderedDict([('name', 'Delhi NCR'),
             ('country', 'IN'),
             ('population', 21.935),
             ('coordinates', LatLong(lat=28.613889, long=77.208889))])

In [59]:
for key, value in delhi._asdict().items():
    print(key + ':', value)

name: Delhi NCR
country: IN
population: 21.935
coordinates: LatLong(lat=28.613889, long=77.208889)


#### Кортежи как неизменяемые списки

In [ ]:
# tuple поддерживает все методы list, 
#     не связанные с изменением элементов, 
#         кроме одного: __reversed__.

# Тем не менее, reversed(my_tuple) все равно работает.

### Получение среза

In [62]:
# Классы последовательностей в Python (list, tuple, str, ...) 
#     поддерживают операции среза.

##### Соглашение об индексации с нуля в Python:

In [71]:
# Последний элемент не включается в срезы и диапазоны;

# Легко понять длину среза | диапазона по конечной позиции:
#     и range(3), и my_list[:3] содержат три элемента;

# Легко вычислить длину среза | диапазона, 
#     если заданы начальная и конечная позиция:
#         достаточно вычислить их разницу stop - start;

# Легко разбить последовательность на две непересекающиеся части
#     по любому индексу:
#         нужно взять my_list[:x] и my_list[x:]

l = [i * 10 for i in range(1, 7)]
assert l[:2] + l[2:] == l

#### Объекты среза

In [75]:
s = 'bicycle'

print(s[::3]) # => операция a:b:c порождает объект среза slice(a, b, c)

print(s[::-1])

print(s[::-2])

bye
elcycib
eccb


#### Многомерные срезы и многоточие

In [77]:
# Оператор [] может принимать несколько срезов, разделенных запятыми:
#     a[m:n, k:l]

# Методы [] __getitem__ и __setitem__ принимают индексы в виде кортежа:
#     для вычисления a[i, j] Python вызывает a.__getitem__((i, j))

In [ ]:
# Многоточие - три отдельных точки - псевдоним объекта Ellipsis,
#     единственного экземпляра класса ellipsis.

# Многоточие можно использовать в качестве части среза:
#     f(a, ..., z) или a[i:...].
#     
#     x[i, ...] equal to x[i, :, :, :]

#### Присваивание срезу

In [82]:
# Изменяемую последовательность можно модифицировать,
#     используя оператор del и нотации среза.

In [5]:
l = list(range(10))
l[2:5] = [20, 30]
l # 2, 3, 4 => 20, 30

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [6]:
del l[5:7]
l # delete индексы 5, 6

[0, 1, 20, 30, 5, 8, 9]

In [7]:
l[3::2] = [11, 22]
l # начиная с индекса 3, заменяем каждый второй элемент на 11, 22

[0, 1, 20, 11, 5, 22, 9]

In [8]:
l[2:5] = [100]
l # элемент 100 занимает место элементов со 2 по 4 индексы  

[0, 1, 100, 22, 9]

In [ ]:
# Когда в левой части присваивания срез,
#     в правой должен находиться итерируемый объект - даже с одним элементом.

### Использование + и * для последовательностей

In [11]:
l = [1, 2, 3]
l * 5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [12]:
5 * 'abcd'

'abcdabcdabcdabcdabcd'

In [30]:
my_list = [[]] * 3
my_list # список, содержащий три ссылки на один и тот же внутренний список

[[], [], []]

In [31]:
my_list[0].append(1) # при изменении одного из списков меняются все три
my_list

[[1], [1], [1]]

#### Построение списка списков

In [6]:
board = [['_'] * 3 for i in range(3)] # создание списка 
board                                 # из трех списков по три элемента

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [34]:
board[1][2] = 'X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

In [8]:
weird_board = [['_'] * 3] * 3
weird_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [9]:
weird_board[1][2] = 'O'
weird_board

[['_', '_', 'O'], ['_', '_', 'O'], ['_', '_', 'O']]

### Составное присваивание последовательностей

In [11]:
# За оператором += стоит специальный метод __iadd__;
# Если метод не реализованЮ то Python вызывает метод __add__.

In [12]:
# Соответственно, идентификатор объекта остается  или изменяется 
#     в зависимости от наличия метода __iadd__.

In [15]:
l = [1, 2, 3]
first_l_id = id(l)

l *= 2  # список изменяется, оставаясь прежним
second_l_id = id(l)

assert first_l_id == second_l_id

In [17]:
t = (1, 2, 3)
first_t_id = id(t)

t *= 2  # неизменяемый объект обновляется
second_t_id = id(t)

assert first_t_id != second_t_id

#### Головоломка: присваивание А +=

In [2]:
t = (1, 2, [30, 40])

t[2] += [50, 60]

TypeError: 'tuple' object does not support item assignment

In [3]:
t

(1, 2, [30, 40, 50, 60])

##### Байт-код помогает понять, что происходит за капотом!

### Метод list.sort и sorted

In [22]:
# Метод list.sort сортирует список на месте, не создавая копию;
# В качестве return он возвращает None.

##### Функции и методы, изменяющие объект на месте, должны возвращать None.

In [2]:
# Недостатком является то, что такие методы невозможно соединить в цепочку;

# Методы, возвращающие новые объекты (например, методы str)
#     можно сцеплять и создавать "текучий" интерфейс.

In [3]:
# Встроенная функция sorted создает и возвращает новый список.

# При этом она принимает любой итерируемый объект,
#     но независимо от этого возвращает новый список.

In [4]:
# Как метод list.sort, так и функция sorted 
#     принимают два необязательных именованных аргумента:

#         - reverse - по умолчанию False, 
#               возвращает элементы в порядке убывания;

#         - key - функция с аргументом, 
#               возвращающая ключ сортировки для каждого элемента:
#                   key=str.lower будет сортировать строки без учета регистра,
#                       а key=len - по длине в символах.

In [5]:
fruits = ['grape', 'raspberry', 'apple', 'banana']
sorted(fruits) # создает новый список

['apple', 'banana', 'grape', 'raspberry']

In [6]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [7]:
sorted(fruits, reverse=True)

['raspberry', 'grape', 'banana', 'apple']

In [9]:
sorted(fruits, key=len)

['grape', 'apple', 'banana', 'raspberry']

In [10]:
sorted(fruits, key=len, reverse=True)

['raspberry', 'banana', 'grape', 'apple']

In [11]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [13]:
fruits.sort()
fruits # изменяет текущий список

['apple', 'banana', 'grape', 'raspberry']

### Средства работы с упорядоченными последовательностями в модуле bisect

In [14]:
# В модуле bisect есть две основные функции:

#     - bisect;
#     - insort.

# Они обе применяют алгоритм двоичной сортировки 
#     для быстрого поиска и вставки элементов 
#         в отсортированную последовательность.

# Мы читали об этом алгоритме в "Грокаем алгоритмы".
#     Его скорость - О(log n) 

#### Поиск средствами bisect

In [17]:
# Функция bisect (haystack, needle) ищет иголку needle в стоге сена haystack.

# Результат - позиция, в которой все элементы до 
#     меньше или равны needle (соответственно, сохраняется порядок).

In [19]:
import bisect
import sys

HAYSTACK = [1, 4, 5, 6, 8, 12, 15, 20, 21, 23, 23, 26, 29, 30]
NEEDLES = [0, 1, 2, 5, 8, 10, 22, 23, 29, 30, 31]

ROW_FMT = '{0:2d} @ {1:2d} {2}{0:<2d}'

def demo(bisect_fn):
    for needle in reversed(NEEDLES):
        position = bisect_fn(HAYSTACK, needle) # получаем точку вставки
        offset = position * ' |' # строим "забор" из черточек
        print(ROW_FMT.format(needle, position, offset)) # печатаем строку
                                                # с иголкой и точкой вставки
if __name__ == '__main__':
    
    if sys.argv[-1] == 'left': # в зависимости от аргумента в командной строке
        bisect_fn = bisect.bisect_left # выбераем функцию bisect
    else:
        bisect_fn = bisect.bisect

print('DEMO:', bisect_fn.__name__) # печатаем заголовок с именем функции
print('haystack ->', ' '.join('%2d' % n for n in HAYSTACK))
demo(bisect_fn)

DEMO: bisect
haystack ->  1  4  5  6  8 12 15 20 21 23 23 26 29 30
31 @ 14  | | | | | | | | | | | | | |31
30 @ 14  | | | | | | | | | | | | | |30
29 @ 13  | | | | | | | | | | | | |29
23 @ 11  | | | | | | | | | | |23
22 @  9  | | | | | | | | |22
10 @  5  | | | | |10
 8 @  5  | | | | |8 
 5 @  3  | | |5 
 2 @  1  |2 
 1 @  1  |1 
 0 @  0 0 


In [ ]:
# Поведение bisect настраивается двумя способами:

#     - Аргументы lo и hi помогают сузить область поиска;

#     - Bisect - она же bisect_right - возвращает точку вставки
#           после существующего элемента в случае, 
#               когда needle совпадает с элементом списка;

#                   bisect_left же возвращает точку перед ним.

In [20]:
def grade(score, breakpoints=[60, 70, 80, 90], grades='FDCBA'):
    i = bisect.bisect(breakpoints, score)
    return grades[i]
# функция grade возвращает букву, соответствующую числовой оценке за экзамен
[grade(score) for score in [33, 99, 77, 70, 89, 90, 100]]

['F', 'A', 'C', 'C', 'B', 'A', 'A']

#### Вставка с помощью функции bisect.insort

In [22]:
# Функция insort(seq, item) вставляет элемент item 
#     в последовательность seq так, чтобы в seq не нарушался порядок.

In [26]:
import bisect
import random

SIZE = 7

random.seed(1729)

my_list = []
for i in range(SIZE):
    new_item = random.randrange(SIZE*2)
    bisect.insort(my_list, new_item)
    print('%2d ->' % new_item, my_list)

10 -> [10]
 0 -> [0, 10]
 6 -> [0, 6, 10]
 8 -> [0, 6, 8, 10]
 7 -> [0, 6, 7, 8, 10]
 2 -> [0, 2, 6, 7, 8, 10]
10 -> [0, 2, 6, 7, 8, 10, 10]


In [27]:
# Как и bisect, функция insort принимает аргументы lo и hi;

# И также существует функция insort_left.

### Когда список не подходит

In [29]:
# В случае, если мы организуем много проверок на вхождение,
#     следует воспользоваться множеством; 
#         Множества не упорядочены, а потому не являются последоватльностями.

#### Массивы

In [32]:
# Тип array.array эффективнее, 
#     когда мы работаем только с числами:

#     - В нем хранятся не объекты float, а упакованные байты;

#     - Он поддерживает как операции над изменяемыми последовательностями,
#           так и дополнительные методы быстрой загрузки и сохранения;

# При создании array задается код типа:
#     буква, определяющая, какой тип C использовать.

In [34]:
from array import array
from random import random
floats = array('d', (random() for i in range(10**7))) # создаем массив
                            # с плавающей точкой двойной точности ('d')
                            # из генераторного выражения
floats[-1]

0.1288579230853678

In [35]:
fp = open('floats.bin', 'wb')
floats.tofile(fp) # сохраняем массив в двоичном формате
fp.close()

In [36]:
floats2 = array('d') # создаем массив с плавающей точкой двойной точности
fp = open('floats.bin', 'rb')
floats2.fromfile(fp, 10**7) # читаются 10 миллионов чисел из двоичного файла
fp.close()
floats2[-1] # читаем последнее число в файле

0.1288579230853678

In [38]:
 floats2 == floats # содержимое обоих массивов совпадает

True

In [39]:
# Если же нам необходимо работать 
#     с большими коллекциями объектов 
#         типа complex и пользовательских классов,
#             следует воспользоваться модулем pickle.

In [ ]:
# Чтобы отсортировать array на месте (аналог list.sort()),
#     следует воспользоваться функцией sorteed:
#         a = array.array(a.typecode, sorted(a))

# Для поддержания массива в отсортированном состоянии
#     при вставке элементов пользуемся bisect.insort

#### Представления областей памяти

In [41]:
# Класс memoryview позволяет работать со срезами массивов,
#     ничего при этом не копируя.

# Memoryview позволяет разделять память 
#     между структурами данных без копирования.

In [42]:
# Memoryview.cast позволет изменить запись нескольких байтов,
#     не перемещая ни одного бита.

# Memoryview.cast возвращает другой объект memoryview,
#     занимающий то же самое место в памяти.

In [45]:
from array import array

numbers = array('h', [-2, -1, 0, 1, 2])

memv = memoryview(numbers) # создаем объект из массива пяти чисел (тип 'h') 
len(memv) 

5

In [46]:
memv[0] # memv видит 5 элементом массива

-2

In [48]:
memv_oct = memv.cast('B') # создаем объект, приведя memv к другому коду
memv_oct.tolist() # экспортируем элементы memv_oct в виде списка

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [49]:
memv_oct[5] = 4 # присваиваем байту со смещением 5 значение 4

In [50]:
numbers # число 0 изменилось на 1024 (4^5)

array('h', [-2, -1, 1024, 1, 2])

In [51]:
# Для нетривиальных численных расчетов 
#     следует использовать библиотеки NumPy и SciPy

#### Библиотеки NumPy и SciPy

In [53]:
import numpy as np
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [54]:
type(a)

numpy.ndarray

In [55]:
a.shape

(12,)

In [56]:
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
a[2]

array([ 8,  9, 10, 11])

In [58]:
a[2, 1]

9

In [59]:
a[:, 1]

array([1, 5, 9])

In [60]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

#### Двусторонние и другие очереди

In [63]:
# Методы .append и .pop позволяют использовать список list
#     как стек или очередь (например, Last In - First Out)
#
# Но вставка и удаление из левого конца списка - дорогая операция,
#     так как приходится сдвигать весь список.

# Для таких операций, как FIFO (First In - First Out), 
#     следует использовать класс collections.deque.

# Deque можно сделать ограниченной (задать максимальную длину),
#     и тогда при заполнении новых элементов старые будут удалться сами.

In [71]:
from collections import deque

dq = deque(range(10), maxlen=10) # maxlen ограничивает число элементов в deque
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
dq.rotate(3) # происходит циклический сдвиг элементов
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6])

In [73]:
dq.rotate(-4)
dq

deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [74]:
dq.appendleft(-1) # при добавлении в заполненную очередь
                  # конечный элемент удаляется: 0
dq

deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
dq.extend([11, 22, 33]) # при добавлении трех элементов справа
dq                      # удалются три элемента слева: -1, 1, 2

deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33])

In [76]:
dq.extendleft([10, 20, 30, 40]) # функция extendleft последовательно добавляет 
dq                              # элементы из аргумента в конец очереди

deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8])

##### Удаление из середины deque производит медленно!

In [78]:
# Эта структура оптимизирована для добавления и удаления элементов
#     только с любого конца.

### Резюме

In [80]:
# Последовательности классифицируются 
#    как на изменяемые и неизменяемые, так и на плоские и контейнерные.

# Контейнерные последовательности более гибкие,
#     но неочевидные при хранении в них изменяемых объектов.

In [81]:
# Списковые включения и генераторные выражения - 
#     эффективный способ инициализации последовательностей.

In [82]:
# Кортежи играют роль как неимзеняемых списков,
#     так и записей с неименованными полями.

# Когда кортеж используется как запись, 
#     следует раскрывать его с помощью распаковки.
# Вспомогательный операнд * делает этот механизм еще удобнее.

# Именованные кортежи, появившиеся недавно, 
#     оптимизируют работу с кортежем как записью
#         благодар низким накладным расходам и дополнительным методам.

In [ ]:
# Получение среза последовательности - хорошая операция,
#     которая становится еще удобнее 
#         благодаря использованию многоточия и многомерных срезов.

In [83]:
# Краткая конкатенация (seq * n) - удобная операция,
#     к которой следует подходить с должной осторожностью.

# Операции += и *= ведут себя по-разному
#     для изменяемых и неизменямых последовательностей.

In [84]:
# Метод sort и функция sorted обладают гибкостью 
#     благодар аргументу key, вычисляющему критерий сортировки.

# Для поддержания последовательности в отсортированном виде
#     элементы следует вставлять функцией bisect.insort.

# Поиск же в отсортированной последовательности 
#     лучше осуществлять с помощью bisect.bisect.

In [ ]:
# Помимо списков и кортежей, в стандартной библиотеке имеются
#     класс array.array и collections.deque.

# Первый широко применяется в пакетах NumPy и SciPy.

# Вторая же позволяет потокобезопасно реализовывать FIFO-LIFO модели. 